/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jdbccon;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author SHESHANT
 */
public class welcome_admin extends javax.swing.JFrame {

    /**
     * Creates new form welcome_admin
     */
    Connection con = null;
    String url = "jdbc:mysql://10.5.18.66:3306/";
    String dbName = "12CS10046";
    String driver = "com.mysql.jdbc.Driver";
    String userName = "12CS10046";
    String password = "btech12";
    String user,pass,sql;
    
    PreparedStatement pst = null;
    boolean a,b,c;
    String my_id = null;
    String dp = "";
    public welcome_admin() {
        initComponents();
        try {
           patient_doctor_id.setVisible(false);
           conform.setVisible(false);
          Class.forName(driver).newInstance();
          con = DriverManager.getConnection(url+dbName,userName,password);
          //st=con.createStatement();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Welcome.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Welcome.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Welcome.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Welcome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        welcome_label = new javax.swing.JLabel();
        id_label = new javax.swing.JLabel();
        patient_doctor_id = new javax.swing.JTextField();
        conform = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        list_of_patients = new javax.swing.JMenuItem();
        list_of_doctors = new javax.swing.JMenuItem();
        patient_details = new javax.swing.JMenuItem();
        test_and_doctor = new javax.swing.JMenuItem();
        doctor_and_patients = new javax.swing.JMenuItem();
        payment_dues = new javax.swing.JMenuItem();
        reports_pending = new javax.swing.JMenuItem();
        patient_test = new javax.swing.JMenuItem();
        tets_doctor = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        change_password = new javax.swing.JMenuItem();
        new_patient = new javax.swing.JMenuItem();
        new_doctor = new javax.swing.JMenuItem();
        exit_patient = new javax.swing.JMenuItem();
        exit_doctor = new javax.swing.JMenuItem();
        update_price = new javax.swing.JMenuItem();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("WELCOME ADMINISTRATOR");

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        welcome_label.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        welcome_label.setText("WELCOME ADMINISTRATOR");

        id_label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        id_label.setForeground(new java.awt.Color(0, 102, 51));

        patient_doctor_id.setEditable(false);
        patient_doctor_id.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        patient_doctor_id.setForeground(new java.awt.Color(0, 102, 51));
        patient_doctor_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patient_doctor_idActionPerformed(evt);
            }
        });

        conform.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        conform.setForeground(new java.awt.Color(0, 102, 102));
        conform.setText("Conform");
        conform.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        conform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conformActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(id_label, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(patient_doctor_id, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117)
                        .addComponent(conform, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(welcome_label, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(266, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(welcome_label, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(206, 206, 206)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(patient_doctor_id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(id_label, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(conform, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(205, Short.MAX_VALUE))
        );

        jMenu1.setText("View");

        list_of_patients.setText("list of patients");
        list_of_patients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_of_patientsActionPerformed(evt);
            }
        });
        jMenu1.add(list_of_patients);

        list_of_doctors.setText("list of doctors");
        list_of_doctors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_of_doctorsActionPerformed(evt);
            }
        });
        jMenu1.add(list_of_doctors);

        patient_details.setText("patient details");
        patient_details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patient_detailsActionPerformed(evt);
            }
        });
        jMenu1.add(patient_details);

        test_and_doctor.setText("tests and corresponding doctors");
        test_and_doctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                test_and_doctorActionPerformed(evt);
            }
        });
        jMenu1.add(test_and_doctor);

        doctor_and_patients.setText("doctors and corresponding patients");
        doctor_and_patients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctor_and_patientsActionPerformed(evt);
            }
        });
        jMenu1.add(doctor_and_patients);

        payment_dues.setText("payment dues");
        payment_dues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payment_duesActionPerformed(evt);
            }
        });
        jMenu1.add(payment_dues);

        reports_pending.setText("reports pending");
        reports_pending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reports_pendingActionPerformed(evt);
            }
        });
        jMenu1.add(reports_pending);

        patient_test.setText("patients under a given test");
        patient_test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patient_testActionPerformed(evt);
            }
        });
        jMenu1.add(patient_test);

        tets_doctor.setText("tests under a given doctor");
        tets_doctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tets_doctorActionPerformed(evt);
            }
        });
        jMenu1.add(tets_doctor);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        change_password.setText("Change password");
        change_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_passwordActionPerformed(evt);
            }
        });
        jMenu2.add(change_password);

        new_patient.setText("new patient");
        new_patient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_patientActionPerformed(evt);
            }
        });
        jMenu2.add(new_patient);

        new_doctor.setText("new doctor");
        new_doctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_doctorActionPerformed(evt);
            }
        });
        jMenu2.add(new_doctor);

        exit_patient.setText("exit patient");
        exit_patient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_patientActionPerformed(evt);
            }
        });
        jMenu2.add(exit_patient);

        exit_doctor.setText("exit doctor");
        exit_doctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_doctorActionPerformed(evt);
            }
        });
        jMenu2.add(exit_doctor);

        update_price.setText("update price");
        update_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_priceActionPerformed(evt);
            }
        });
        jMenu2.add(update_price);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void new_patientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_patientActionPerformed
        new_patient np = new new_patient();
        np.show();// TODO add your handling code here:
    }//GEN-LAST:event_new_patientActionPerformed

    private void exit_patientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_patientActionPerformed
       patient_doctor_id.setVisible(true);
        conform.setVisible(true);
        patient_doctor_id.setEditable(true);
        id_label.setText("Enter patient id here");
        dp = "PATIENT";
    }//GEN-LAST:event_exit_patientActionPerformed

    private void patient_doctor_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patient_doctor_idActionPerformed
        
    }//GEN-LAST:event_patient_doctor_idActionPerformed

    private void conformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conformActionPerformed
            
//        patient_doctor_id.setEditable(false);
            String id = patient_doctor_id.getText();
            
            if(id.length() == 0)
            {
                JOptionPane.showMessageDialog(null, "please enter suitable id","ERROR",JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                Statement st = null;
                ResultSet rs = null;
                Statement st1 = null;
                try {
                    
                    st = con.createStatement();
                    st1 = con.createStatement();
                    if(dp.equals("DOCTOR"))
                    {
                        sql = "select * from DOCTOR where DOCTOR_ID = '"+id+"'";
                        rs = st.executeQuery(sql);
                        if(!(rs.next()))
                        {
                            JOptionPane.showMessageDialog(null, "id not found for doctor","ERROR",JOptionPane.ERROR_MESSAGE);
                        }
                        else
                        {
                            sql = "delete from DOCTOR where DOCTOR_ID = '"+id+"'";
                            int rowsAffected = st1.executeUpdate(sql);
                            if(rowsAffected == 0)
                            {
                                JOptionPane.showMessageDialog(null, "Data not deleted","ERROR",JOptionPane.WARNING_MESSAGE);
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(null, "Data successfully deleted","MESSAGE",JOptionPane.INFORMATION_MESSAGE);
                            }
                        }
                    }
                    if(dp.equals("PATIENT"))
                    {
                        sql = "select * from PATIENT where PATIENT_ID = '"+id+"'";
                        rs = st.executeQuery(sql);
                        if(!(rs.next()))
                        {
                            JOptionPane.showMessageDialog(null, "id not found for PATIENT","ERROR",JOptionPane.ERROR_MESSAGE);
                        }
                        else
                        {
                            sql = "delete from PATIENT where PATIENT_ID = '"+id+"'";
                            int rowsAffected = st1.executeUpdate(sql);
                            if(rowsAffected == 0)
                            {
                                JOptionPane.showMessageDialog(null, "Data not deleted","ERROR",JOptionPane.WARNING_MESSAGE);
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(null, "Data successfully deleted","MESSAGE",JOptionPane.INFORMATION_MESSAGE);
                            }
                        }
                    }
                    if(dp.length() == 0)
                    {
                        JOptionPane.showMessageDialog(null, "there is some error","ERROR",JOptionPane.ERROR_MESSAGE);
                    }
                    
                } catch (SQLException ex) {
                    Logger.getLogger(welcome_admin.class.getName()).log(Level.SEVERE, null, ex);
                }
                finally{
        try{
            if(rs != null)
            {
                rs.close();
            }
           
           if(pst != null)
            {
                pst.close();
            }
           if(st != null)
            {
                st.close();
            }
            
    }       catch (SQLException ex) {
        JOptionPane.showMessageDialog(null,null,String.valueOf(ex) ,JOptionPane.WARNING_MESSAGE);
                Logger.getLogger(Welcome.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
            }
    }//GEN-LAST:event_conformActionPerformed

    private void list_of_patientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_of_patientsActionPerformed
            admin_table at = new admin_table();
            at.set_id("p");
            at.show();// TODO add your handling code here:
    }//GEN-LAST:event_list_of_patientsActionPerformed

    private void list_of_doctorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_of_doctorsActionPerformed
        admin_table at = new admin_table();
            at.set_id("d");
            at.show();// TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_list_of_doctorsActionPerformed

    private void change_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_passwordActionPerformed
            admin_password ap = new admin_password();
            ap.show();// TODO add your handling code here:
    }//GEN-LAST:event_change_passwordActionPerformed

    private void new_doctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_doctorActionPerformed
            new_doctor nd = new new_doctor();
            nd.show();// TODO add your handling code here:
    }//GEN-LAST:event_new_doctorActionPerformed

    private void exit_doctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_doctorActionPerformed
        patient_doctor_id.setVisible(true);
           conform.setVisible(true);
        patient_doctor_id.setEditable(true);
        id_label.setText("Enter doctor id here");
        dp = "DOCTOR";
    }//GEN-LAST:event_exit_doctorActionPerformed

    private void patient_detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patient_detailsActionPerformed
        patient_bill pb = new patient_bill();
        pb.show();
    }//GEN-LAST:event_patient_detailsActionPerformed

    private void payment_duesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payment_duesActionPerformed
        admin_table at = new admin_table();
        at.show_paid_status();
        at.show();
    }//GEN-LAST:event_payment_duesActionPerformed

    private void update_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_priceActionPerformed
        test_cost tc = new test_cost();
        tc.show();
    }//GEN-LAST:event_update_priceActionPerformed

    private void test_and_doctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_test_and_doctorActionPerformed
        admin_table at = new admin_table();
            at.test_and_doctor();
            at.show();
    }//GEN-LAST:event_test_and_doctorActionPerformed

    private void doctor_and_patientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctor_and_patientsActionPerformed
        admin_table at = new admin_table();
        at.doctor_and_patient();
        at.show();
    }//GEN-LAST:event_doctor_and_patientsActionPerformed

    private void reports_pendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reports_pendingActionPerformed
        admin_table at = new admin_table();
        at.report_pending();
        at.show();
    }//GEN-LAST:event_reports_pendingActionPerformed

    private void patient_testActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patient_testActionPerformed
        test_patient tp = new test_patient();
        tp.show();
    }//GEN-LAST:event_patient_testActionPerformed

    private void tets_doctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tets_doctorActionPerformed
        Doctor_test dt = new Doctor_test();
        dt.show();
    }//GEN-LAST:event_tets_doctorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(welcome_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(welcome_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(welcome_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcome_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new welcome_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem change_password;
    private javax.swing.JButton conform;
    private javax.swing.JMenuItem doctor_and_patients;
    private javax.swing.JMenuItem exit_doctor;
    private javax.swing.JMenuItem exit_patient;
    private javax.swing.JLabel id_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem list_of_doctors;
    private javax.swing.JMenuItem list_of_patients;
    private javax.swing.JMenuItem new_doctor;
    private javax.swing.JMenuItem new_patient;
    private javax.swing.JMenuItem patient_details;
    private javax.swing.JTextField patient_doctor_id;
    private javax.swing.JMenuItem patient_test;
    private javax.swing.JMenuItem payment_dues;
    private javax.swing.JMenuItem reports_pending;
    private javax.swing.JMenuItem test_and_doctor;
    private javax.swing.JMenuItem tets_doctor;
    private javax.swing.JMenuItem update_price;
    private javax.swing.JLabel welcome_label;
    // End of variables declaration//GEN-END:variables
}
